### ISSUE TITLE
Maximum range criteria not enforced

### ISSUE THREAD

**Issue by james-ward** [thedropbears/pycrescendo#143]
Shooter component will end up at minimum angle when outside the ranges in the lookup table, but the flywheels will still be spinning.

Suggest using `np.interp(..., right=0.0)` in the shooter component.

There may also be issues with hysteresis at the maximum range that need to be dealt with to stop constant stop-start if the robot is spending time around that range.

**Comment by mlists** [comment]
Is the motivation for this to conserve power? By running the flywheels at the maximum range speed we will be ready to fire the moment we enter our range. If we do go down this route, I think it should be applied symmetrically since the same problems exist below minimum range as above the maximum. To get this behavior without the stop-start I think we should consider adding zero speed points beyond our max range to get a smooth transition up to the maximum range speed.
